REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_PASSWORD = '123456'
REDIS_NAME_HTTP = 'http_proxies'
REDIS_NAME_HTTPS = 'https_proxies'

VALIDATE_URL_HTTP = 'http://baidu.com'
VALIDATE_URL_HTTPS = 'https://baidu.com'

# 代理检测间隔时间
CHECK_INTERVAL = 120
PROXY_PROTECT = 'FETCH_TTL'
PROXY_REFRESH = 'REFRESH_TTL'
PROTECT_SEC = 300
REFRESH_SEC = 7200
PROXY_LOW = 10
PROXY_EXHAUST = 3
LOOP_DELAY = 30